### ISSUE TITLE
HW 3 Comments

### ISSUE THREAD

**Issue by sttung** [ammore/DAT_SF_16#5]
@ammore Good work! Numbered comments by sections below.
1. README: Great descriptions and write-ups for the features in the dataset! The write-ups clarifying what each of the features meant and its significance were particularly helpful. 
2. KNN
3. Dataframe setup: cool way of renaming the columns - I hadn't thought of indexing by number and renaming (I named the columns directly in the first line of code), but I could see myself using this approach in the future. Especially helpful for defining features so I don't have to type out the names again! The only suggestion I have here would be considering using shorter feature names. 
4. Cross validation: a shorter way to get to scores would be to use sklearn cross_validation.cross_val_score - that way you don't have to define the function each time :)
5. Naive Bayes: 
6. Dataframe: since you're working with the same dataset, you could reference the dataframe you built out earlier for the KNN model instead of re-reading in the CSV data. Added bonus of less code writing! 
7. Counts: comments for these would be helpful to clarify why they're important for building out the Bayes model. 
8. Approach: since we're working with all numeric values and a binary label, the model can be built out without having to train it on text recognition, so I think some of the lines of code for that could be removed. 

@ghego @breucopter - this homework (and review) was quite helpful for seeing the different approaches taken to get to the same end result.

**Comment by ghego** [comment]
@ammore : did I get it right that the HW file is HW_03/lab_05_inst_AMM.ipynb ? 
If so, a couple of suggestions:
- have a look at some of your classmates repos for how they are organizing the HW material
- you should really start with an empty new notebook and build your calculation there, instead of starting from the lab code and trying to adapt it. I know it will be hard at the beginning, but it will help you much more to understand and improve
- also, using the lab notebook leaves a lot of text that doesn't pertain to the HW and it makes it difficult to read

Let me know how we can help!

Keep rocking!

@sttung : that's what the HW is for :)
